version: "2"

services:
    jenkins:
        image: jenkinsci/blueocean
        container_name: blueocean
        volumes:
            - "../volumes/jenkins_home:/var/jenkins_home"
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - "50000:50000"
            - "8080:8080"
