version: '2'
services:
    hassio:
        image: homeassistant/raspberrypi2-homeassistant
        volumes:
            - ./config:/config
            - /etc/localtime:/etc/localtime:ro
        network_mode: "host"
        container_name: hassio
